# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edcd2bf92ef512c263af0e1dddd0c55cc102a9e2037196d07654e4d3454ad48e8d90c5c4b92d3367e4e3efabeceb4b869435b87dd61c33efa8e98a871f57c021

test:
  secret_key_base: d170308ad91b3f8ca0e40c42b94675106975812d5dffc2d0fa75cb10aee317efd73729dde7a7f24fc8e3b7ce5d4bd92c30031dbbefd48296d7fd54ff11353ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
